modLoader = "javafml" #mandatory
loaderVersion = "[36,)"
license = "GNU Affero General Public License v3.0"
issueTrackerURL="https://github.com/Sonnenlicht-as/BizarreFans/issues/" #optional
[[mods]] #mandatory
modId = "bizarre_fans" #mandatory
version = "1.0" #mandatory
#${file.jarVersion}
displayName = "Bizarre_Fans" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="BizarreFans.png" #optional
authors = "sonnenlicht" #optional
description = '''
Adding some crafts
'''

[[dependencies.bizarre_fans]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.bizarre_fans]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
